[package]
name = "dmenu-manager"
version = "0.1.0"
edition = "2018"
authors = ["Abyss <abyssabuse@pm.me>"]
description = "Dmenu wrapper allowing the use of a toml file to configure dmenu."
license = "Unlicense"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["wrap_help"] }
atty = "0.2.14"
anyhow = "1.0.42"
tap = "1.0.1"
colored = "2.0.0"
serde = { version = "1.0.127", features = ["derive"] }
toml = "0.5.8"
radix_fmt = "1.0.0"

[profile.release]
lto = true
codegen-units = 1
