[package]
name = "dmenu-manager"
version = "0.1.0"
edition = "2021"
authors = ["Abyss <abyssability@pm.me>"]
description = "Dmenu wrapper allowing the use of a toml file to configure dmenu."
license = "CC0-1.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["cargo", "env", "wrap_help"] }
owo-colors = { version = "3.1", features = ["supports-color"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
anyhow = "1.0"
atty = "0.2"
radix_fmt = "1.0"

[profile.release]
lto = true
codegen-units = 1
