    #    See the toml website, [[https://toml.io/]], for more info on the toml format
    #    example config, not default

    #  `entries` is an array of values
    #  A valid value can be a single string or a table
    entries = [
        #  a string will be interpreted as a command to run
        "name and command",
        #  run: the command to run, also used as its name in the menu
        #  group: all items are ordered by group; the default group is `0` (zero)
        #  Larger groups are displayed first, negative groups are last
        { run = "command and name", group = 5 },
        { run = "last", group = -100 },
    ]

    #  `menu` is a table of name-value pairs.
    #  The name will be displayed by dmenu;
    #  if selected, the command will be executed.
    [menu]
    name = "command to run"
    #  The name can be quoted to allow spaces (and more) in names.
    "space separated name" = { run = "echo 'why?'", group = 1 }
    #  Triple quotes are multi-line strings.
    small-script = """
    ls -la | count > file-count.tmp
    firefox
    """

    [menu."most important"]
    run = "echo 'incredibly important'"
    group = 9001

    [menu.foo]
    run = "ls"


    [config]
    #  Allows "custom" commands, not specified in `entries` or `menu`.
    #  Type a command into dmenu, then press shift+enter to execute it.
    ad-hoc = true
    #  Specify a custom shell. The default is `sh`.
    shell = "fish"
    #  Prepend a number to each name.
    numbered = true
    #  A custom separator can be specified as a string.
    separator = " -- "
    #  Disable separator between numbers and names.
    #separator = false

    #  Passes config to dmenu as flags.
    #  See `man dmenu` for more info.
    [config.dmenu]
    #  Give dmenu a custom prompt.
    prompt = "dmenu:"
    #  Give dmenu a custom font.
    font = "Hack Nerd Font:size=16"
    #  Give dmenu a custom background color.
    background = "#002b36"
    #  Give dmenu a custom font color.
    foreground = "#839496"
    #  Give dmenu a custom background color for the selected menu entry.
    selected-background = "#268bd2"
    #  Give dmenu a custom font color for the selected menu entry.
    selected-foreground = "#002b36"
    #  Make dmenu appear at the bottom of the screen.
    bottom = true
    #  Make dmenu grab keyboard input before reading stdin.
    #fast = true
    #  Make dmenu match menu entries case sensitively while searching.
    #case-sensitive = true
    #  Make dmenu list items vertically using multiple lines.
    lines = 5
    #  Make dmenu display on a different monitor.
    #monitor = 0
    #  Make dmenu embed into `window-id`.
    #window-id = "0"
